// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Go Data Cache
Time based Cache implementation in Go


    Schemes:
      http
    Host: localhost
    BasePath: /v1/cache
    Version: 1.0
    Contact: Shivang Goswami<shivang.goswami@outlook.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
