// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Time based Cache implementation in Go",
    "title": "Go Data Cache",
    "contact": {
      "name": "Shivang Goswami",
      "email": "shivang.goswami@outlook.com"
    },
    "version": "1.0"
  },
  "basePath": "/v1/cache",
  "paths": {
    "/fetch": {
      "get": {
        "description": "Get Data Stored in Cache\n",
        "tags": [
          "DataCacheOperations"
        ],
        "summary": "Get Data",
        "parameters": [
          {
            "type": "string",
            "name": "key",
            "in": "query"
          },
          {
            "minimum": 1,
            "type": "integer",
            "name": "index",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "key value data",
            "schema": {
              "$ref": "#/definitions/cacheCollection"
            }
          },
          "default": {
            "description": "Generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        },
        "x-visibility": "public"
      }
    },
    "/store": {
      "post": {
        "description": "Store Data in Cache\n",
        "tags": [
          "DataCacheOperations"
        ],
        "summary": "Store Data",
        "parameters": [
          {
            "name": "params",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/cache"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Cache Data stored Successfully"
          },
          "default": {
            "description": "Generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        },
        "x-visibility": "public"
      }
    }
  },
  "definitions": {
    "cache": {
      "type": "object",
      "required": [
        "key",
        "value",
        "expiration"
      ],
      "properties": {
        "expiration": {
          "description": "expiration duration",
          "type": "string",
          "x-example": "5m"
        },
        "key": {
          "description": "key value",
          "type": "string",
          "maxLength": 20,
          "minLength": 1,
          "x-example": "hello"
        },
        "value": {
          "description": "data value",
          "x-example": "gopher data cache"
        }
      },
      "x-visibility": "public"
    },
    "cacheCollection": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/cache"
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "description": "http error code",
          "type": "integer",
          "format": "int64",
          "x-example": 401
        },
        "message": {
          "description": "http error message",
          "type": "string",
          "x-example": "forbidden"
        }
      },
      "x-visibility": "public"
    }
  },
  "tags": [
    {
      "description": "Operations related to Cache manipulation",
      "name": "DataCacheOperations"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Time based Cache implementation in Go",
    "title": "Go Data Cache",
    "contact": {
      "name": "Shivang Goswami",
      "email": "shivang.goswami@outlook.com"
    },
    "version": "1.0"
  },
  "basePath": "/v1/cache",
  "paths": {
    "/fetch": {
      "get": {
        "description": "Get Data Stored in Cache\n",
        "tags": [
          "DataCacheOperations"
        ],
        "summary": "Get Data",
        "parameters": [
          {
            "type": "string",
            "name": "key",
            "in": "query"
          },
          {
            "minimum": 1,
            "type": "integer",
            "name": "index",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "key value data",
            "schema": {
              "$ref": "#/definitions/cacheCollection"
            }
          },
          "default": {
            "description": "Generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        },
        "x-visibility": "public"
      }
    },
    "/store": {
      "post": {
        "description": "Store Data in Cache\n",
        "tags": [
          "DataCacheOperations"
        ],
        "summary": "Store Data",
        "parameters": [
          {
            "name": "params",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/cache"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Cache Data stored Successfully"
          },
          "default": {
            "description": "Generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        },
        "x-visibility": "public"
      }
    }
  },
  "definitions": {
    "cache": {
      "type": "object",
      "required": [
        "key",
        "value",
        "expiration"
      ],
      "properties": {
        "expiration": {
          "description": "expiration duration",
          "type": "string",
          "x-example": "5m"
        },
        "key": {
          "description": "key value",
          "type": "string",
          "maxLength": 20,
          "minLength": 1,
          "x-example": "hello"
        },
        "value": {
          "description": "data value",
          "x-example": "gopher data cache"
        }
      },
      "x-visibility": "public"
    },
    "cacheCollection": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/cache"
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "description": "http error code",
          "type": "integer",
          "format": "int64",
          "x-example": 401
        },
        "message": {
          "description": "http error message",
          "type": "string",
          "x-example": "forbidden"
        }
      },
      "x-visibility": "public"
    }
  },
  "tags": [
    {
      "description": "Operations related to Cache manipulation",
      "name": "DataCacheOperations"
    }
  ]
}`))
}
